version: '3.5'

services:
  local-dynamo:
    container_name: local-dynamo
    image: localstack/localstack:0.11.2
    ports:
      - 8000:4566
    environment:
      SERVICES: dynamodb
      START_WEB: 0

