version: '3'

networks:
  mynetwork:
    driver: bridge

services:
  infinispan-server:
    image: infinispan/server:latest
    environment:
      - USER=Titus Bramble
      - PASS=Shambles
    ports:
      - "11222:11222"
    container_name: infinispan
