# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

jobs:
- job: Build
  timeoutInMinutes: 60
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    imageName: 'quarkus:$(build.buildId)'
  steps:

  - task: Maven@3
    displayName: 'Maven Build'
    inputs:
      goals: 'verify org.ec4j.maven:editorconfig-maven-plugin:0.0.10:check'
      options: '--settings azure-mvn-settings.xml -Pquarkus -Dnative-image.docker-build -Pnative -Dnative-image.xmx=4g'

