version: "3.5"

services:
  redis:
    image: redis:5.0.6
    ports:
      - "6379:6379"

  weather-producer:
    image: weather-producer:1.0
    build:
      context: ./weather-producer
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    depends_on:
      - redis
    environment:
      - QUARKUS_REDIS_HOSTS=redis://redis:6379
      - PRODUCER_RATE=${RATE:-500}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}

  weather-consumer:
    image: weather-consumer:1.0
    build:
      context: ./weather-consumer
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    ports:
      - "8080-8083:8080"
    depends_on:
      - redis
      - weather-producer
    environment:
      - QUARKUS_REDIS_HOSTS=redis://redis:6379
      - QUARKUS_HTTP_PORT=8080
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
