version: "3.5"

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  producer:
    image:  quarkus-quickstarts/redis-streams-producer:1.0
    build:
      context: ./producer
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    depends_on:
      - redis
    environment:
      - QUARKUS_REDIS_HOSTS=redis://redis:6379
      - PRODUCER_RATE=${RATE:-500}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}

  aggregator:
    image:  quarkus-quickstarts/kafka-streams-aggregator:1.0
    build:
      context: ./aggregator
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    ports:
      - "8080-8083:8080"
    depends_on:
      - redis
      - producer
    environment:
      - QUARKUS_REDIS_HOSTS=redis://redis:6379
      - QUARKUS_HTTP_PORT=8080
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}