version: '3.5'

services:
  localstack:
    image: localstack/localstack:0.11.2
    ports:
      - 8010:4566
    environment:
      SERVICES: sqs
      START_WEB: 0
    networks:
      - localstack


  quarkus-kms:
    image: quarkus/amazon-sqs-quickstart
    container_name: quarkus-sqs
    ports:
    - 8080:8080
    networks:
      - localstack
    entrypoint: ["./application", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.sqs.endpoint-override=http://localstack:4566"]

networks:
  localstack:
    name: localstack

